[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "template_project_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module", "abi3-py311"] }
